USE bfoew88ofvz2mfhfv5eg

CREATE TABLE USUARIO (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	cpf CHAR(11) UNIQUE,
	nome VARCHAR(100),
	senha VARCHAR(25),
	enderecoId INTEGER,
	id_contato INTEGER,
	PRIMARY KEY(id)
);


CREATE TABLE ENDERECO_USU (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	logradouro VARCHAR(200),
	bairro VARCHAR(100),
	cidade VARCHAR(50),
	uf CHAR(2),
	cep CHAR(8),
	PRIMARY KEY(id)
);


CREATE TABLE contato_org (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	email VARCHAR(100) UNIQUE,
	celular CHAR(11) UNIQUE,
	PRIMARY KEY(id)
);


CREATE TABLE contato_social (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	instagram VARCHAR(255) UNIQUE,
	facebook VARCHAR(255) UNIQUE,
	tiktok VARCHAR(255) UNIQUE,
	x VARCHAR(255) UNIQUE,
	whatsapp VARCHAR(255) UNIQUE,
	PRIMARY KEY(id)
);


CREATE TABLE perfils (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	nome VARCHAR(20),
	foto BLOB,
	PRIMARY KEY(id)
);


CREATE TABLE planos (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	titulo VARCHAR(25) UNIQUE,
	descricao VARCHAR(200) UNIQUE,
	valor  NUMERIC,
	PRIMARY KEY(id)
);


CREATE TABLE perfil orgazinador (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	foto BLOB,
	nome VARCHAR(100),
	PRIMARY KEY(id)
);


CREATE TABLE organizadores (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	cnpj CHAR(14) UNIQUE,
	razao social VARCHAR(50) UNIQUE,
	PRIMARY KEY(id)
);


CREATE TABLE post (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	foto do post BLOB,
	descricao VARCHAR(200),
	`titulo ` VARCHAR(30),
	comentario VARCHAR(255),
	curtidas NUMERIC,
	PRIMARY KEY(id)
);


CREATE TABLE pratica esportivas (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	mapa BLOB UNIQUE,
	PRIMARY KEY(id)
);


CREATE TABLE eventos (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`foto ` BLOB,
	descricao VARCHAR(15000),
	valor NUMERIC,
	categoria VARCHAR(100),
	PRIMARY KEY(id)
);


CREATE TABLE categoria (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	nome categoria VARCHAR(70) UNIQUE,
	PRIMARY KEY(id)
);


CREATE TABLE endereço_eventos (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	logradouro VARCHAR(200),
	bairro VARCHAR(100),
	cidade VARCHAR(50),
	uf CHAR(2),
	cep CHAR(8),
	PRIMARY KEY(id)
);


CREATE TABLE endereco_prat (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	logradouro VARCHAR(200),
	bairro VARCHAR(100),
	cidade VARCHAR(50),
	uf CHAR(2),
	cep CHAR(8),
	PRIMARY KEY(id)
);


ALTER TABLE USUARIO
ADD FOREIGN KEY(id) REFERENCES planos(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE USUARIO
ADD FOREIGN KEY(id) REFERENCES ENDERECO_USU(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE post
ADD FOREIGN KEY(id) REFERENCES USUARIO(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE perfils
ADD FOREIGN KEY(id) REFERENCES USUARIO(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE perfils
ADD FOREIGN KEY(id) REFERENCES contato_social(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE contato_social
ADD FOREIGN KEY(id) REFERENCES perfil orgazinador(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE perfil orgazinador
ADD FOREIGN KEY(id) REFERENCES organizadores(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE organizadores
ADD FOREIGN KEY(id) REFERENCES contato_org(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE organizadores
ADD FOREIGN KEY(id) REFERENCES eventos(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE eventos
ADD FOREIGN KEY(id) REFERENCES categoria(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE endereco_prat
ADD FOREIGN KEY(id) REFERENCES pratica esportivas(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE pratica esportivas
ADD FOREIGN KEY(id) REFERENCES USUARIO(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE eventos
ADD FOREIGN KEY(id) REFERENCES USUARIO(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;